name: Deploy GitHub Pages (Simple)

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags
  workflow_dispatch:  # Allow manual triggering
    inputs:
      version:
        description: 'Version to deploy (e.g., 5.0.2)'
        required: false
        type: string

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Extract version information
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ github.event.inputs.version }}" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" = "push" ] && [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          else
            # Fallback to package.json version
            echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
          fi
          echo "YEAR=$(date +%Y)" >> $GITHUB_OUTPUT
          
      - name: Get extension ID
        id: extension-id  
        run: |
          echo "EXTENSION_ID=lmllmppkplhgnmjnklnkngmijnlogink" >> $GITHUB_OUTPUT
          
      - name: Process HTML template
        run: |
          # Replace template variables in the HTML
          sed -i "s/{{VERSION}}/${{ steps.version.outputs.VERSION }}/g" docs/index.html
          sed -i "s/{{EXTENSION_ID}}/${{ steps.extension-id.outputs.EXTENSION_ID }}/g" docs/index.html  
          sed -i "s/{{YEAR}}/${{ steps.version.outputs.YEAR }}/g" docs/index.html
          sed -i "s/{{INSTALL_COUNT}}/10000/g" docs/index.html
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
          
      - name: Success notification
        run: |
          echo "✅ GitHub Pages deployed successfully!"
          echo "🔗 Site URL: https://danatkinson.github.io/Fuskr/"
          echo "📦 Version: ${{ steps.version.outputs.VERSION }}"
          echo "🆔 Extension ID: ${{ steps.extension-id.outputs.EXTENSION_ID }}"
